twist_mux:
  ros__parameters:
    # 입력 소스 목록 (맵 구조)
    topics:
      nav:
        topic: cmd_vel_nav
        timeout: 0.3
        priority: 1
      teleop:
        topic: cmd_vel_teleop
        timeout: 0.3
        priority: 2
      emergency:
        topic: cmd_vel_emergency
        timeout: 0.5
        priority: 3

    # 락 목록 (맵 구조)
    locks:
      emergency_stop:
        topic: emergency_stop
        timeout: 0.0
        priority: 255
